/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BpButtonComp: typeof import('./components/BpButton/BpButtonComp.vue')['default']
    BpLoad: typeof import('./components/BpLoad/index.vue')['default']
    BpLoadComp: typeof import('./components/BpLoad/BpLoadComp.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    LangCollapse: typeof import('./components/TopBar/LangCollapse.vue')['default']
    Menu: typeof import('./components/TopBar/Menu.vue')['default']
    README: typeof import('./components/BpLoad/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./components/TopBar/index.vue')['default']
    WalletBtn: typeof import('./components/WalletBtn/index.vue')['default']
  }
}
